# Generated by Django 5.2.5 on 2025-10-17 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='consistency_score',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
